export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILED = 'FETCH_CONFIG_FAILED';
export const CHOOSE_CONFIG = 'CHOOSE_CONFIG';
export const CHANGE_CONFIG_STARTED = 'CHANGE_CONFIG_STARTED';
export const CHANGE_CONFIG_SUCCESS = 'CHANGE_CONFIG_SUCCESS';
export const CHANGE_CONFIG_FAILED = 'CHANGE_CONFIG_FAILED';
export const DELETE_CONFIG_STARTED = 'DELETE_CONFIG_STARTED';
export const DELETE_CONFIG_SUCCESS = 'DELETE_CONFIG_SUCCESS';
export const DELETE_CONFIG_FAILED = 'DELETE_CONFIG_FAILED';
export const CREATE_CONFIG_STARTED = 'CREATE_CONFIG_STARTED';
export const CREATE_CONFIG_SUCCESS = 'CREATE_CONFIG_SUCCESS';
export const CREATE_CONFIG_FAILED = 'CREATE_CONFIG_FAILED';


/*
* Загружаем данные для отображения групп
* */
export const FETCH_PROFILES_STARTED = 'FETCH_PROFILES_STARTED';
export const FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS';
export const FETCH_PROFILES_FAILED = 'FETCH_PROFILES_FAILED';

/*
* Удаляем группы
* */
export const DELETE_PROFILE = 'DELETE_PROFILE '
export const DELETE_PROFILES_STARTED = 'DELETE_PROFILES_STARTED';
export const DELETE_PROFILES_SUCCESS = 'DELETE_PROFILES_SUCCESS';
export const DELETE_PROFILES_FAILED = 'DELETE_PROFILES_FAILED';

/*
* Изменяем положение групп
* */
export const CHANGE_PROFILE_POSITION = 'CHANGE_PROFILE_POSITION';
export const CHANGE_PROFILE_POSITION_STARTED = 'CHANGE_PROFILE_POSITION_STARTED';
export const CHANGE_PROFILE_POSITION_FAILED = 'CHANGE_PROFILE_POSITION_FAILED';
export const CHANGE_PROFILE_POSITION_SUCCESS = 'CHANGE_PROFILE_POSITION_SUCCESS'

export const CLOSE_PROFILE_MODAL = 'CLOSE_PROFILE_MODAL';

/*
* Загружаем данные для рендера профиля
* */
export const FETCH_PROFILE_STARTED = 'FETCH_PROFILE_STARTED';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILED = 'FETCH_PROFILE_FAILED';

export const ADD_NEW_PROFILE = 'ADD_NEW_PROFILE';
export const ADD_NEW_PROFILE_STARTED = 'ADD_NEW_PROFILE_STARTED';
export const ADD_NEW_PROFILE_SUCCESS = 'ADD_NEW_PROFILE_SUCCESS';
export const ADD_NEW_PROFILE_FAILED = 'ADD_NEW_PROFILE_FAILED';

export const UPDATE_PROFILE_STARTED = 'UPDATE_PROFILE_STARTED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'


